[env]
FORCE_COLOR=1 # Enable full colour terminal outputs when running with mise

HOST_PORT=3000 # The host port to use when running with docker compose
PORT=3000 # The port octocord will listen on for HTTP requests

DISCORD_TOKEN = { value = "your-discord-bot-token", redact = true }
DISCORD_APP_ID = { value = "your-discord-app-id", redact = true }
DISCORD_PUBLIC_KEY = { value = "your-discord-public-key", redact = true }
DISCORD_GUILD_ID = "your-discord-service-id"

GITHUB_APP_ID = { value = "your-github-app-id", redact = true }
GITHUB_APP_INSTALLATION_ID = { value = "your-github-app-install-id", redact = true }
GITHUB_APP_PRIVATE_KEY_PEM = { value = "your-github-app-private-key-pem", redact = true }
GITHUB_OWNER = "your-github-org"
GITHUB_REPO = "your-github-repo"