[tools]
node = "24.8.0"
pnpm = "10.17.0"

[tasks.dev]
run = "pnpm tsx watch src/index.ts"

[tasks.build]
run = "tsc"

[tasks.start]
run = "node --enable-source-maps dist/index.js"

[tasks.test]
run = "echo 'no tests yet 🤡'"

[tasks.register-commands]
run = "pnpm tsx src/utils/registerCommands.ts"